### ISSUE TITLE
Link to the pretrained models

### ISSUE THREAD

**Issue by jbertrand89** [xianyongqin/few-shot-video-classification#1]
Hello! Thanks a lot for this work. I would like to download the pre-trained models, specifically the fine-tuned models, but the link currently doesn't work. Is it possible to add it again please?

**Comment by jbertrand89** [comment]
@xianyongqin @yqxian any updates regarding the links to the models?

**Comment by xianyongqin** [comment]
Hi, the link is correct. Please try again by copying and pasting the link address to your browser.

**Comment by jbertrand89** [comment]
It does work, I must have selected the wrong path. Thanks so much!
